# Introduction
<b>NumPy (Numerical Python)</b> is an open source Python library that’s used in almost every field of science and engineering. It’s the universal standard for working with numerical data in Python, and it’s at the core of the scientific Python and PyData ecosystems.
<br>
<br>
<br>
<b>Interesting Read</b> : [The first image of a Balck Hole](https://numpy.org/case-studies/blackhole-image/)

<img src='https://numpy.org/images/content_images/cs/blackhole.jpg' width='300' align='left'>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<br>
<br>
<br>


[Most part of this notebook is adopted from `numpy` & `datetime` docs]

# Imports

In [49]:
import numpy as np # `np` acts as an alias to the package you with to import, here numpy
np.__version__

'1.19.4'

<b>Where is this package numpy that we just imported sitting?</b>

In [18]:
np

<module 'numpy' from '/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/__init__.py'>

<b>How to read the documentation for an any given function?</b>

In [15]:
np?

In [14]:
?np

<b>How to read the documentation for an any given function, along side source code?</b>

In [10]:
np??

In [16]:
??np

# Python & `array`

<b>One of the major reasons for ease of use of Python is its dynamic typing, i.e we dont need to specify which type a variable might assume a value of, which is not the case in most of the other languages such as C & Java</b>

In C++ we need to define a variable and the type i.e

`int age = 24`

In Python we do away with the dataype of that particular variable, i.e

`age=24` is more than sufficient, although if you want to be more specific, we can always use
`age:int=24`

In [30]:
age1=24
age2:int=42

print(f'age1={age1}(Type=({type(age1)})), age2={age2}(Type=({type(age2)}))')


age1=24(Type=(<class 'int'>)), age2=42(Type=(<class 'int'>))


[A Python 🐍  list is more than just a list](https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html#A-Python-List-Is-More-Than-Just-a-List) -  Python Data Science Handbook , Jake VanderPlas

To allow for the dynamic typing, we have to pay a cost while creating a list with mutliple datatypes, which is that the list object now need to keep track of all the elements within, and each of these elements are an Object in itseleves.


In [33]:
L=[1,'Achintya', 3.14, True]
L

[1, 'Achintya', 3.14, True]

In [37]:
print(type(L[1]))

<class 'str'>


<b>So how do we overcome this, is there a way?</b>

Yes! Use Python's `array` module, 

Available TypeCodes are :

    Type code   C Type             Minimum size in bytes
    'b'         signed integer     1
    'B'         unsigned integer   1
    'u'         Unicode character  2 (see note)
    'h'         signed integer     2
    'H'         unsigned integer   2
    'i'         signed integer     2
    'I'         unsigned integer   2
    'l'         signed integer     4
    'L'         unsigned integer   4
    'q'         signed integer     8 (see note)
    'Q'         unsigned integer   8 (see note)
    'f'         floating point     4
    'd'         floating point     8


In [62]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<b>Can we append a different datatype to the list and make an array object?</b>

In [63]:
L+=['some string']
A = array.array('i', L)
A

TypeError: an integer is required (got type str)

# `numpy` to the rescue

<b>Creating a simple numpy array</b>

[NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html)

All of the elements in a NumPy array should be homogenous. 
Can you notice the difference between the two?

In [67]:
np.array(L[:-1])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.array(L)

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'some string'],
      dtype='<U21')

Numpy `ndarray` module will not throw an error, but instead try to upcast the values(elements) to a suitable common datatype: [List of Numpy DataTypes](https://numpy.org/devdocs/user/basics.types.html)

Creating a Basic Numpy Array :

<img src='https://numpy.org/doc/stable/_images/np_array.png'>

In [68]:
np.array([1,2,3])

array([1, 2, 3])

In [69]:
np.array([1,2,3.14])

array([1.  , 2.  , 3.14])

# Basics - Array Generation

<b>Creating an array of a particular `size=2` 1D with all values `1`</b>

In [73]:
np.zeros(2, dtype=int) # 1D Array

array([0, 0])

<b>Creating an array of a particular `size=(2,2)` 2D with all values `0`</b>

In [78]:
np.ones((2,2), dtype=int) # 2D Array

array([[1, 1],
       [1, 1]])

<b>Creating an array of a particular `size=(2,2,2)` 3D with all values `0`</b>

In [84]:
np.ones((2,2,2), dtype=int) # 3D Array and so on...

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

<b>Creating an array containg range of equally spaced intervals</b>

In [85]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

<b>Create an array with values that are spaced linearly in a specified interval</b>

In [90]:
np.linspace(-20, 20, 12)

array([-20.        , -16.36363636, -12.72727273,  -9.09090909,
        -5.45454545,  -1.81818182,   1.81818182,   5.45454545,
         9.09090909,  12.72727273,  16.36363636,  20.        ])

<b>Create an array with random values between [0, 1)</b>

In [103]:
np.random.random((3, 3))

array([[0.91984011, 0.43286515, 0.88622096],
       [0.708858  , 0.49844346, 0.33204096],
       [0.92016405, 0.19900804, 0.72728854]])

<b>Create an array with random integer of the size (m,n) all sampled from a given range</b>

In [108]:
np.random.randint(-2,20,(3, 4))

array([[ 7, 10, 17,  3],
       [15, 11, -1, 19],
       [-2,  2, 15, 18]])

# Indicing and Reshaping Numpy Array

Indicing an Numpy `ndarray` is same as indicing a Python🐍 `list`

<img src='https://numpy.org/doc/stable/_images/np_indexing.png'>

In [116]:
npL = np.array(L)
npL

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [126]:
print('Element at 0th index : ', npL[0])
print('Element at -1 index, i.e last index', npL[-1])
print('Elements from 1 and on index, SubArray', npL[1:])
print('Elements upto -2 index, SubArray', npL[:-2])
print('Elements from -2 index, SubArray', npL[-2:])
print('Elements from index 2 to -4, SubArray', npL[-2:])
print('Every second element', npL[::2])
print('Every third element', npL[::3])
print('Elements reversed', npL[::-1])

Element at 0th index :  0
Element at -1 index, i.e last index 19
Elements from 1 and on index, SubArray [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Elements upto -2 index, SubArray [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]
Elements from -2 index, SubArray [18 19]
Elements from index 2 to -4, SubArray [18 19]
Every second element [ 0  2  4  6  8 10 12 14 16 18]
Every third element [ 0  3  6  9 12 15 18]
Elements reversed [19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


<b>Reshaping an array</b>

In [127]:
npL=np.array([1,2,3])
npL

array([1, 2, 3])

In [128]:
npL[:, np.newaxis]

array([[1],
       [2],
       [3]])

In [129]:
npL[np.newaxis, :]

array([[1, 2, 3]])

# Broadcasting

<img src='https://numpy.org/doc/stable/_images/np_multiply_broadcasting.png'>

<img src='https://numpy.org/doc/stable/_images/np_aggregation.png'>

In [131]:
L = list(range(5))
L

[0, 1, 2, 3, 4]

In [132]:
L+2 # Throws an error!

TypeError: can only concatenate list (not "int") to list

In [139]:
print('Addition       : ', np.array(L)+2)
print('Multiplication : ', np.array(L)*2)
print('Division       : ', np.array(L)/2)
print('Moduluo        : ', np.array(L)%2)
print('Power          : ', np.array(L)**2)


Addition       :  [2 3 4 5 6]
Multiplication :  [0 2 4 6 8]
Division       :  [0.  0.5 1.  1.5 2. ]
Moduluo        :  [0 1 0 1 0]
Power          :  [ 0  1  4  9 16]


Will highly recommed that you go through the Broadcasting Operations :[Numpy Broadcasting](https://numpy.org/doc/stable/user/absolute_beginners.html#broadcasting)

# Datetimes in Python

Since this talk is about Time Series Forecasting, we will take a deep dive into [Numpy `datetime64`](https://numpy.org/doc/stable/reference/arrays.datetime.html#datetimes-and-timedeltas)

<b>But before we dive deep into the Numpy `datetime64` datetime datatype, lets first see the pythons inbuilt `datetime` library</b>

## Python Native `datetime`


`datetime.strftime` Format Codes

<table class="docutils align-default">
<colgroup>
<col style="width: 15%">
<col style="width: 43%">
<col style="width: 32%">
<col style="width: 9%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Directive</p></th>
<th class="head"><p>Meaning</p></th>
<th class="head"><p>Example</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">%a</span></code></p></td>
<td><p>Weekday as locale’s
abbreviated name.</p></td>
<td><div class="line-block">
<div class="line">Sun, Mon, …, Sat
(en_US);</div>
<div class="line">So, Mo, …, Sa
(de_DE)</div>
</div>
</td>
</tr>
<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">%A</span></code></p></td>
<td><p>Weekday as locale’s full name.</p></td>
<td><div class="line-block">
<div class="line">Sunday, Monday, …,
Saturday (en_US);</div>
<div class="line">Sonntag, Montag, …,
Samstag (de_DE)</div>
</div>
</td>
</tr>
<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">%w</span></code></p></td>
<td><p>Weekday as a decimal number,
where 0 is Sunday and 6 is
Saturday.</p></td>
<td><p>0, 1, …, 6</p></td>
</tr>
<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">%d</span></code></p></td>
<td><p>Day of the month as a
zero-padded decimal number.</p></td>
<td><p>01, 02, …, 31</p></td>
</tr>
<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">%b</span></code></p></td>
<td><p>Month as locale’s abbreviated
name.</p></td>
<td><div class="line-block">
<div class="line">Jan, Feb, …, Dec
(en_US);</div>
<div class="line">Jan, Feb, …, Dez
(de_DE)</div>
</div>
</td>
</tr>
<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">%B</span></code></p></td>
<td><p>Month as locale’s full name.</p></td>
<td><div class="line-block">
<div class="line">January, February,
…, December (en_US);</div>
<div class="line">Januar, Februar, …,
Dezember (de_DE)</div>
</div>
</td>
</tr>
<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">%m</span></code></p></td>
<td><p>Month as a zero-padded
decimal number.</p></td>
<td><p>01, 02, …, 12</p></td>
</tr>
<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">%y</span></code></p></td>
<td><p>Year without century as a
zero-padded decimal number.</p></td>
<td><p>00, 01, …, 99</p></td>
</tr>
<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">%Y</span></code></p></td>
<td><p>Year with century as a decimal
number.</p></td>
<td><p>0001, 0002, …, 2013,
2014, …, 9998, 9999</p></td>
</tr>
<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">%H</span></code></p></td>
<td><p>Hour (24-hour clock) as a
zero-padded decimal number.</p></td>
<td><p>00, 01, …, 23</p></td>
</tr>
<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">%I</span></code></p></td>
<td><p>Hour (12-hour clock) as a
zero-padded decimal number.</p></td>
<td><p>01, 02, …, 12</p></td>
</tr>
<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">%p</span></code></p></td>
<td><p>Locale’s equivalent of either
AM or PM.</p></td>
<td><div class="line-block">
<div class="line">AM, PM (en_US);</div>
<div class="line">am, pm (de_DE)</div>
</div>
</td>
</tr>
<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">%M</span></code></p></td>
<td><p>Minute as a zero-padded
decimal number.</p></td>
<td><p>00, 01, …, 59</p></td>
</tr>
<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">%S</span></code></p></td>
<td><p>Second as a zero-padded
decimal number.</p></td>
<td><p>00, 01, …, 59</p></td>
</tr>
<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">%f</span></code></p></td>
<td><p>Microsecond as a decimal
number, zero-padded on the
left.</p></td>
<td><p>000000, 000001, …,
999999</p></td>
</tr>
<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">%z</span></code></p></td>
<td><p>UTC offset in the form
<code class="docutils literal notranslate"><span class="pre">±HHMM[SS[.ffffff]]</span></code> (empty
string if the object is
naive).</p></td>
<td><p>(empty), +0000,
-0400, +1030,
+063415,
-030712.345216</p></td>
</tr>
<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">%Z</span></code></p></td>
<td><p>Time zone name (empty string
if the object is naive).</p></td>
<td><p>(empty), UTC, GMT</p></td>
</tr>
<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">%j</span></code></p></td>
<td><p>Day of the year as a
zero-padded decimal number.</p></td>
<td><p>001, 002, …, 366</p></td>
</tr>
<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">%U</span></code></p></td>
<td><p>Week number of the year
(Sunday as the first day of
the week) as a zero padded
decimal number. All days in a
new year preceding the first
Sunday are considered to be in
week 0.</p></td>
<td><p>00, 01, …, 53</p></td>
</tr>
<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">%W</span></code></p></td>
<td><p>Week number of the year
(Monday as the first day of
the week) as a decimal number.
All days in a new year
preceding the first Monday
are considered to be in
week 0.</p></td>
<td><p>00, 01, …, 53</p></td>
</tr>
<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">%c</span></code></p></td>
<td><p>Locale’s appropriate date and
time representation.</p></td>
<td><div class="line-block">
<div class="line">Tue Aug 16 21:30:00
1988 (en_US);</div>
<div class="line">Di 16 Aug 21:30:00
1988 (de_DE)</div>
</div>
</td>
</tr>
<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">%x</span></code></p></td>
<td><p>Locale’s appropriate date
representation.</p></td>
<td><div class="line-block">
<div class="line">08/16/88 (None);</div>
<div class="line">08/16/1988 (en_US);</div>
<div class="line">16.08.1988 (de_DE)</div>
</div>
</td>
</tr>
<tr class="row-even"><td><p><code class="docutils literal notranslate"><span class="pre">%X</span></code></p></td>
<td><p>Locale’s appropriate time
representation.</p></td>
<td><div class="line-block">
<div class="line">21:30:00 (en_US);</div>
<div class="line">21:30:00 (de_DE)</div>
</div>
</td>
</tr>
<tr class="row-odd"><td><p><code class="docutils literal notranslate"><span class="pre">%%</span></code></p></td>
<td><p>A literal <code class="docutils literal notranslate"><span class="pre">'%'</span></code> character.</p></td>
<td><p>%</p></td>
</tr>
</tbody>
</table>

Another useful library to look at are : [dateutils](https://dateutil.readthedocs.io/en/stable/), [pytz-Handles TimeZones](http://pytz.sourceforge.net)


In [180]:
from datetime import datetime, timedelta

<b>Getting a particular datetime</b>

In [181]:
datetime(year=2020, month=12, day=7, hour=12, minute=23)

datetime.datetime(2020, 12, 7, 12, 23)

<b>Getting Now!</b>

In [186]:
datetime.now()

datetime.datetime(2020, 11, 27, 0, 9, 25, 371690)

<b>Getting a string representation of the datetime</b>

For the format codes, see the table in the header.

In [249]:
current_time = datetime.now()
print('Current year                                 :', current_time.strftime('%Y'))
print('Current year-month                           :', current_time.strftime('%Y-%m'))
print('Current year-month-date                      :', current_time.strftime('%Y-%m-%d'))
print('Current year-month-date-hour-minutes-seconds :', current_time.strftime('%Y-%m-%d %H-%M-%S'))
print('Current weeknumber                           :', current_time.strftime('%W'))
print('Current 12-hour clock time                   :', current_time.strftime('%I:%M:%S %p'))
print('Current Month name                           :', current_time.strftime('%B'))
print('Current Month name Abbreviation              :', current_time.strftime('%b'))
print('Current Week Day Number                      :', current_time.strftime('%w'))
print('Current Week Day                             :', current_time.strftime('%A'))

Current year                                 : 2020
Current year-month                           : 2020-11
Current year-month-date                      : 2020-11-27
Current year-month-date-hour-minutes-seconds : 2020-11-27 00-21-23
Current weeknumber                           : 47
Current 12-hour clock time                   : 12:21:23 AM
Current Month name                           : November
Current Month name Abbreviation              : Nov
Current Week Day Number                      : 5
Current Week Day                             : Friday


<b>Inferring datetime from a string</b>


In [250]:
datetime.strptime('2020-11-27 00-15-51', '%Y-%m-%d %H-%M-%S')

datetime.datetime(2020, 11, 27, 0, 15, 51)

<b>`datetime` atrributes</b>

In [251]:
[k for k in current_time.__dir__() if '_' not in k]

['now',
 'utcnow',
 'fromtimestamp',
 'utcfromtimestamp',
 'strptime',
 'combine',
 'fromisoformat',
 'date',
 'time',
 'timetz',
 'ctime',
 'timetuple',
 'timestamp',
 'utctimetuple',
 'isoformat',
 'utcoffset',
 'tzname',
 'dst',
 'replace',
 'astimezone',
 'hour',
 'minute',
 'second',
 'microsecond',
 'tzinfo',
 'fold',
 'min',
 'max',
 'resolution',
 'fromordinal',
 'fromisocalendar',
 'today',
 'strftime',
 'isocalendar',
 'isoweekday',
 'toordinal',
 'weekday',
 'year',
 'month',
 'day']

<b>Operations using `Timedelta`</b>

In [330]:
print('Current Time              : ', datetime.now())
print('Time 10 days prior        : ', datetime.now()-timedelta(days=10))
print('Time 10 hours prior       : ', datetime.now()-timedelta(hours=10))
print('Time 1 day, 3 hours prior : ', datetime.now()-timedelta(days=1, hours=10))

Current Time              :  2020-11-27 00:36:17.555281
Time 10 days prior        :  2020-11-17 00:36:17.555813
Time 10 hours prior       :  2020-11-26 14:36:17.555948
Time 1 day, 3 hours prior :  2020-11-25 14:36:17.556069


In [337]:
# Divinding two timedeltas
timedelta(days=1) / timedelta(hours=4)

6.0

## `dateutils` Package

In [439]:
# https://dateutil.readthedocs.io/en/stable/exercises/index.html
from dateutil.rrule import rrule
from dateutil.parser import parse
from dateutil.rrule import MO, TU, WE, TH, FR, SA, SU, YEARLY, DAILY, MONTHLY, WEEKLY
from dateutil.relativedelta import relativedelta

<b>Playing around with `relativedelta`</b>

In [403]:
print('Current Time              : ', datetime.now())
print('Time 10 days prior        : ', datetime.now()+relativedelta(months=3))

Current Time              :  2020-11-27 02:52:32.410145
Time 10 days prior        :  2021-02-27 02:52:32.410751


In [405]:
t1 = datetime.now()
t2 = t1+relativedelta(microseconds=3)
relativedelta(t2,t1)

relativedelta(microseconds=+3)

One month before one year

In [409]:
t1+relativedelta(years=+1, months=-1)

datetime.datetime(2021, 10, 27, 2, 53, 33, 686780)

Last Friday of this month

In [412]:
t1+relativedelta(day=31, weekday=FR(-1))

datetime.datetime(2020, 11, 27, 2, 53, 33, 686780)

Next Monday

In [419]:
t1+relativedelta(weekday=MO(+1))

datetime.datetime(2020, 11, 30, 2, 53, 33, 686780)

Next Monday, But not today!

In [420]:
t1+relativedelta(day=1, weekday=MO(+1))

datetime.datetime(2020, 11, 2, 2, 53, 33, 686780)

Whats my age?

In [435]:
birthdate = '1996-11-09'
print('My Age : ', relativedelta(datetime.now(), parse(birthdate)))

My Age :  relativedelta(years=+24, days=+18, hours=+3, minutes=+6, seconds=+37, microseconds=+343226)


<b>Playing around with `rrule`</b>

In [442]:
# Give me next 4 consecutive dates
list(rrule(DAILY, count=4, dtstart=current_time))

[datetime.datetime(2020, 11, 27, 0, 44, 6),
 datetime.datetime(2020, 11, 28, 0, 44, 6),
 datetime.datetime(2020, 11, 29, 0, 44, 6),
 datetime.datetime(2020, 11, 30, 0, 44, 6)]

In [443]:
# Give me next 4, every other date
list(rrule(DAILY, count=4, dtstart=current_time, interval=2))

[datetime.datetime(2020, 11, 27, 0, 44, 6),
 datetime.datetime(2020, 11, 29, 0, 44, 6),
 datetime.datetime(2020, 12, 1, 0, 44, 6),
 datetime.datetime(2020, 12, 3, 0, 44, 6)]

In [446]:
# Give me last friday of next 10 months
list(rrule(MONTHLY, count=10, dtstart=current_time, byweekday=FR(-1)))

[datetime.datetime(2020, 11, 27, 0, 44, 6),
 datetime.datetime(2020, 12, 25, 0, 44, 6),
 datetime.datetime(2021, 1, 29, 0, 44, 6),
 datetime.datetime(2021, 2, 26, 0, 44, 6),
 datetime.datetime(2021, 3, 26, 0, 44, 6),
 datetime.datetime(2021, 4, 30, 0, 44, 6),
 datetime.datetime(2021, 5, 28, 0, 44, 6),
 datetime.datetime(2021, 6, 25, 0, 44, 6),
 datetime.datetime(2021, 7, 30, 0, 44, 6),
 datetime.datetime(2021, 8, 27, 0, 44, 6)]

In [449]:
# Give me last friday of next 10 months
list(rrule(MONTHLY, count=10, dtstart=current_time, byweekday=FR(-1)))

[datetime.datetime(2020, 11, 27, 0, 44, 6),
 datetime.datetime(2020, 12, 25, 0, 44, 6),
 datetime.datetime(2021, 1, 29, 0, 44, 6),
 datetime.datetime(2021, 2, 26, 0, 44, 6),
 datetime.datetime(2021, 3, 26, 0, 44, 6),
 datetime.datetime(2021, 4, 30, 0, 44, 6),
 datetime.datetime(2021, 5, 28, 0, 44, 6),
 datetime.datetime(2021, 6, 25, 0, 44, 6),
 datetime.datetime(2021, 7, 30, 0, 44, 6),
 datetime.datetime(2021, 8, 27, 0, 44, 6)]

In [451]:
# Every other month on the 1st and last Sunday of the month for 10 occurrences.
list(rrule(MONTHLY, interval=2, 
           count=10, dtstart=current_time,
           byweekday=(SU(+1),SU(-1))))

[datetime.datetime(2020, 11, 29, 0, 44, 6),
 datetime.datetime(2021, 1, 3, 0, 44, 6),
 datetime.datetime(2021, 1, 31, 0, 44, 6),
 datetime.datetime(2021, 3, 7, 0, 44, 6),
 datetime.datetime(2021, 3, 28, 0, 44, 6),
 datetime.datetime(2021, 5, 2, 0, 44, 6),
 datetime.datetime(2021, 5, 30, 0, 44, 6),
 datetime.datetime(2021, 7, 4, 0, 44, 6),
 datetime.datetime(2021, 7, 25, 0, 44, 6),
 datetime.datetime(2021, 9, 5, 0, 44, 6)]

<b>Well this seems sufficient right? Then why did `numpy` create its own datatype `datetime64`?</b>

In [292]:
print(current_time, 'of type : ', type(current_time))
current_time+20

2020-11-27 00:21:23.251964 of type :  <class 'datetime.datetime'>


TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'int'

In [298]:
# Try to play around with the format, say 'D', 'M', 'Y', 'h'...
np_current_time = np.datetime64(current_time, 'D')
print(np_current_time, 'of type : ', type(np_current_time))
np_current_time+20

2020-11-27 of type :  <class 'numpy.datetime64'>


numpy.datetime64('2020-12-17')

In [453]:
np_current_time+np.arange(12)

array(['2020-11-27', '2020-11-28', '2020-11-29', '2020-11-30',
       '2020-12-01', '2020-12-02', '2020-12-03', '2020-12-04',
       '2020-12-05', '2020-12-06', '2020-12-07', '2020-12-08'],
      dtype='datetime64[D]')

<b>Thats why!</b>, And also because its an homogeneous way of representaion

## Numpy `datetime64`


<p>The Datetime and Timedelta data types support a large number of time
units, as well as generic units which can be coerced into any of the
other units based on input data.</p>
<p>Datetimes are always stored based on POSIX time (though having a TAI
mode which allows for accounting of leap-seconds is proposed), with
an epoch of 1970-01-01T00:00Z. This means the supported dates are
always a symmetric interval around the epoch, called “time span” in the
table below.</p>
<p>The length of the span is the range of a 64-bit integer times the length
of the date or unit.  For example, the time span for ‘W’ (week) is exactly
7 times longer than the time span for ‘D’ (day), and the time span for
‘D’ (day) is exactly 24 times longer than the time span for ‘h’ (hour).</p>
<p>Here are the date units:</p>
<table class="docutils align-default" id="arrays-dtypes-dateunits">
<colgroup>
<col style="width: 11%">
<col style="width: 22%">
<col style="width: 32%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Code</p></th>
<th class="head"><p>Meaning</p></th>
<th class="head"><p>Time span (relative)</p></th>
<th class="head"><p>Time span (absolute)</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p>Y</p></td>
<td><p>year</p></td>
<td><p>+/- 9.2e18 years</p></td>
<td><p>[9.2e18 BC, 9.2e18 AD]</p></td>
</tr>
<tr class="row-odd"><td><p>M</p></td>
<td><p>month</p></td>
<td><p>+/- 7.6e17 years</p></td>
<td><p>[7.6e17 BC, 7.6e17 AD]</p></td>
</tr>
<tr class="row-even"><td><p>W</p></td>
<td><p>week</p></td>
<td><p>+/- 1.7e17 years</p></td>
<td><p>[1.7e17 BC, 1.7e17 AD]</p></td>
</tr>
<tr class="row-odd"><td><p>D</p></td>
<td><p>day</p></td>
<td><p>+/- 2.5e16 years</p></td>
<td><p>[2.5e16 BC, 2.5e16 AD]</p></td>
</tr>
</tbody>
</table>
<p>And here are the time units:</p>
<table class="docutils align-default" id="arrays-dtypes-timeunits">
<colgroup>
<col style="width: 11%">
<col style="width: 22%">
<col style="width: 32%">
<col style="width: 36%">
</colgroup>
<thead>
<tr class="row-odd"><th class="head"><p>Code</p></th>
<th class="head"><p>Meaning</p></th>
<th class="head"><p>Time span (relative)</p></th>
<th class="head"><p>Time span (absolute)</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p>h</p></td>
<td><p>hour</p></td>
<td><p>+/- 1.0e15 years</p></td>
<td><p>[1.0e15 BC, 1.0e15 AD]</p></td>
</tr>
<tr class="row-odd"><td><p>m</p></td>
<td><p>minute</p></td>
<td><p>+/- 1.7e13 years</p></td>
<td><p>[1.7e13 BC, 1.7e13 AD]</p></td>
</tr>
<tr class="row-even"><td><p>s</p></td>
<td><p>second</p></td>
<td><p>+/- 2.9e11 years</p></td>
<td><p>[2.9e11 BC, 2.9e11 AD]</p></td>
</tr>
<tr class="row-odd"><td><p>ms</p></td>
<td><p>millisecond</p></td>
<td><p>+/- 2.9e8 years</p></td>
<td><p>[ 2.9e8 BC,  2.9e8 AD]</p></td>
</tr>
<tr class="row-even"><td><p>us</p></td>
<td><p>microsecond</p></td>
<td><p>+/- 2.9e5 years</p></td>
<td><p>[290301 BC, 294241 AD]</p></td>
</tr>
<tr class="row-odd"><td><p>ns</p></td>
<td><p>nanosecond</p></td>
<td><p>+/- 292 years</p></td>
<td><p>[  1678 AD,   2262 AD]</p></td>
</tr>
<tr class="row-even"><td><p>ps</p></td>
<td><p>picosecond</p></td>
<td><p>+/- 106 days</p></td>
<td><p>[  1969 AD,   1970 AD]</p></td>
</tr>
<tr class="row-odd"><td><p>fs</p></td>
<td><p>femtosecond</p></td>
<td><p>+/- 2.6 hours</p></td>
<td><p>[  1969 AD,   1970 AD]</p></td>
</tr>
<tr class="row-even"><td><p>as</p></td>
<td><p>attosecond</p></td>
<td><p>+/- 9.2 seconds</p></td>
<td><p>[  1969 AD,   1970 AD]</p></td>
</tr>
</tbody>
</table>

In [299]:
# Simple ISO Date
np.datetime64('2020-12-07'), type(np.datetime64('2020-12-07'))

(numpy.datetime64('2020-12-07'), numpy.datetime64)

In [300]:
np.datetime64('2005-02')

numpy.datetime64('2005-02')

In [301]:
np.datetime64('2005-02-25 03:30')

numpy.datetime64('2005-02-25T03:30')

In [334]:
# Changing resolution of the time display and then try yourself
np.datetime64('2005-02-01T01:20', 'ms')

numpy.datetime64('2005-02-01T01:20:00.000')

In [335]:
np.timedelta64(1,'W') / np.timedelta64(1,'D')

7.0

In [360]:
# Changing resolution of the time and then try yourself
current_time = datetime.now()
np_current_time = np.datetime64(current_time, 'D')
np_current_time_added = np_current_time+np.arange(12)
np_current_time_added

array(['2020-11-27', '2020-11-28', '2020-11-29', '2020-11-30',
       '2020-12-01', '2020-12-02', '2020-12-03', '2020-12-04',
       '2020-12-05', '2020-12-06', '2020-12-07', '2020-12-08'],
      dtype='datetime64[D]')

In [365]:
# Handling Buisness Days

# The first business day on or after a date
np.busday_offset(np_current_time, 0, roll='forward', weekmask='1111100')

numpy.datetime64('2020-11-27')

In [366]:
# The first business day strictly after a date:
np.busday_offset(np_current_time, -1, roll='forward')

numpy.datetime64('2020-11-26')

# Random Testing Space